[package]
name = "sight"
version = "0.1.0"
authors = ["rchudin <rus.chudin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
image = "0.23.11"
